apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
spec:
  selector:
    matchLabels:
      app: spring-music
  replicas: {{.Values.deploy.replicas}}
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - name: spring-music
        image: "{{.Values.deploy.image}}:{{.Values.deploy.imageTag}}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "1.0"
          limits:
            memory: "1024Mi"
            cpu: "2.0"
        ports:
        - containerPort: {{.Values.deploy.containerPort}}
        env:
        - name: RUNTIME
          value: kubernetes
        - name: SPRING_PROFILES_ACTIVE
          value: cosmosdb
        - name: COSMOSDB_URI
          value: "{{.Values.deploy.cosmosConnectString}}"