apiVersion: v1
kind: Service
metadata:
  name: spring-music
  labels:
    app: spring-music
spec:
  type: "{{.Values.service.type}}" 
  ports:
  - name: http
    protocol: TCP
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
  selector:
    app: spring-music          