mixins:
  - exec
  - kubernetes

credentials:
  - name: kubeconfig
    path: /root/.kube/config

name: kubernetes 
version: 0.1.0
description: "An example Porter bundle with Kubernetes"
tag: getporter/kubernetes:v0.1.0

install:
  - kubernetes:
      description: "Create NGINX Deployment"
      manifests:
        - manifests/nginx
      wait: true
      outputs:
        - name: IP_ADDRESS
          resourceType: service
          resourceName: nginx-deployment
          jsonPath: "{.spec.clusterIP}"
  - exec:
      description: "Echo the IP Address"
      command: bash
      flags:
        c: "echo 'You will find the service at {{bundle.outputs.IP_ADDRESS}}'"

uninstall:
  - kubernetes:
      description: "Uninstall Hello World"
      manifests:
        - manifests/nginx
      wait: true

outputs:
  - name: IP_ADDRESS
    type: string
