# Default values for chart

deploy:
  replicas: 1
  image: "chzbrgr71/spring-music"
  imageTag: "v4"
  containerPort: 8080
  cosmosConnectString: "dynamic"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080